build: bump rust to 1.85
Without this fix, using 1.83, a fresh build of the container failed,
displaying error:

  error: failed to parse manifest at `/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/base64ct-1.8.0/Cargo.toml`

  Caused by:
    feature `edition2024` is required

    The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
    Consider trying a newer version of Cargo (this may require the nightly release).
    See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
  Error: building at STEP "RUN cargo build --release": while running runtime: exit status 101

Had there been a committed lockfile, this wouldn't have happened, but
now that it's here we need to update the toolchain, or else manually
downgrade specific crates, and I don't want to mess around with the
latter.